#S.Langa 22522719<br>
</br> #S.SHELEMBE 22506130<br>
</br> #SI NUTLI 22404967<br>
 </br> # NM Nzama 22510310

In [35]:
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
sales=pd.read_csv('Sales Data.csv')

In [37]:
sales.head(10)

,Order ID,Year,Month,Date,Province,Salesperson,Product,Sales Volume,Average Transaction Price,Total Sales,Profit Amount,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,zl101,2019,1,16,Shanghai,De Tang,Product 1,587,22,12914.0,4062.0,NaN,NaN,NaN
1,zl102,2019,1,16,Shenzhen,De Tang,Product 2,30,31,930.0,570.0,NaN,NaN,NaN
2,zl103,2019,1,16,Shenzhen,Bang Li,Product 3,577,31,17887.0,6530.0,NaN,NaN,NaN
3,zl104,2019,1,16,Shanghai,De Tang,Product 1,571,31,17701.0,15853.0,NaN,NaN,NaN
4,zl105,2019,1,16,Shenzhen,Xiangfang Ding,Product 2,80,7,560.0,318.0,NaN,NaN,NaN
5,zl106,2019,1,16,Shandong,Bang Li,Product 4,614,17,10438.0,3403.0,NaN,NaN,NaN
6,zl107,2019,1,16,Shenzhen,Dezhu Zhao,Product 3,715,26,18590.0,3804.0,NaN,NaN,NaN
7,zl108,2019,1,16,Shenzhen,Xiangfang Ding,Product 2,612,9,5508.0,2221.0,NaN,NaN,NaN
8,zl109,2019,1,16,Beijing,De Tang,Product 5,232,32,7424.0,7310.0,NaN,NaN,NaN
9,zl110,2019,1,16,Shandong,Zonghong Wang,Product 1,714,17,12138.0,2132.0,NaN,NaN,NaN

In [38]:
print(dir(sales))

['Date', 'Month', 'Product', 'Province', 'Salesperson', 'T', 'Year', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_arith_method_with_reindex', '_as_manager', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_create_data_for_split_and_tight_to_dict', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item_cache', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_nocopy', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_copy', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_item_cache', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [39]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1501 entries, 0 to 1500
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Order ID                   1501 non-null   object
 1   Year                       1501 non-null   int64
 2   Month                      1501 non-null   int64
 3   Date                       1501 non-null   int64
 4   Province                   1501 non-null   object
 5   Salesperson                1501 non-null   object
 6   Product                    1501 non-null   object
 7   Sales Volume               1501 non-null   int64
 8   Average Transaction Price  1501 non-null   int64
 9   Total Sales                1501 non-null   float64
 10  Profit Amount              1501 non-null   float64
 11  Unnamed: 11                0 non-null      float64
 12  Unnamed: 12                0 non-null      float64
 13  Unnamed: 13                1 non-null      object
dtypes: float64(4), int64(5), object(5)
memory usage: 164.3+ KB

In [40]:
odata.dropna(inplace=True)

In [41]:
'The total number of rows after removing all rows:{}'.format(sales.shape[0])

'The total number of rows after removing all rows:1501'

In [42]:
sales.dropna(axis=1,how='all')

,Order ID,Year,Month,Date,Province,Salesperson,Product,Sales Volume,Average Transaction Price,Total Sales,Profit Amount,Unnamed: 13
0,zl101,2019,1,16,Shanghai,De Tang,Product 1,587,22,12914.0,4062.0,NaN
1,zl102,2019,1,16,Shenzhen,De Tang,Product 2,30,31,930.0,570.0,NaN
2,zl103,2019,1,16,Shenzhen,Bang Li,Product 3,577,31,17887.0,6530.0,NaN
3,zl104,2019,1,16,Shanghai,De Tang,Product 1,571,31,17701.0,15853.0,NaN
4,zl105,2019,1,16,Shenzhen,Xiangfang Ding,Product 2,80,7,560.0,318.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1496,zl1597,2022,12,16,Shenzhen,De Tang,Product 4,729,15,10935.0,10163.0,NaN
1497,zl1598,2022,12,16,Beijing,Bang Li,Product 2,226,36,8136.0,867.0,NaN
1498,zl1599,2022,12,16,Guangdong,De Tang,Product 2,659,9,5931.0,1451.0,NaN
1499,zl1600,2022,12,16,Shenzhen,Bang Li,Product 4,728,33,24024.0,17898.0,NaN
1500,zl1601,2022,12,16,Shandong,Dezhu Zhao,Product 5,640,14,8960.0,3187.0,NaN

In [43]:
sales.drop_duplicates(['Year','Order ID','Salesperson','Product'],inplace=True)

In [44]:
sales = sales.drop(columns=['Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'])

In [45]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1501 entries, 0 to 1500
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Order ID                   1501 non-null   object
 1   Year                       1501 non-null   int64
 2   Month                      1501 non-null   int64
 3   Date                       1501 non-null   int64
 4   Province                   1501 non-null   object
 5   Salesperson                1501 non-null   object
 6   Product                    1501 non-null   object
 7   Sales Volume               1501 non-null   int64
 8   Average Transaction Price  1501 non-null   int64
 9   Total Sales                1501 non-null   float64
 10  Profit Amount              1501 non-null   float64
dtypes: float64(2), int64(5), object(4)
memory usage: 129.1+ KB

In [46]:
odata.shape

(0, 14)

In [47]:
len(sales)

1501

In [48]:
sales.sort_values (by='Sales Volume',ascending=False,inplace=True)

In [49]:
sales.to_csv("cleaned_sales_data.csv", index=False)

In [51]:
 sales.head(10)

,Order ID,Year,Month,Date,Province,Salesperson,Product,Sales Volume,Average Transaction Price,Total Sales,Profit Amount
268,zl369,2019,9,16,Guangdong,Zonghong Wang,Product 1,780,8,6240.0,5878.0
1054,zl1155,2021,11,16,Shandong,De Tang,Product 3,780,28,21840.0,15134.0
1493,zl1594,2022,12,16,Beijing,Dezhu Zhao,Product 5,779,11,8569.0,2066.0
540,zl641,2020,6,16,Guangdong,Xiangfang Ding,Product 3,778,32,24896.0,2350.0
891,zl992,2021,6,16,Shandong,Xiangfang Ding,Product 3,778,32,24896.0,18227.0
984,zl1085,2021,9,16,Shanghai,Zonghong Wang,Product 4,778,11,8558.0,3611.0
490,zl591,2020,5,16,Guangdong,Bang Li,Product 4,778,32,24896.0,1637.0
937,zl1038,2021,7,16,Shanghai,Dezhu Zhao,Product 2,777,12,9324.0,9142.0
1224,zl1325,2022,5,16,Shenzhen,Zonghong Wang,Product 3,777,20,15540.0,10464.0
1353,zl1454,2022,9,16,Shandong,Dezhu Zhao,Product 5,777,25,19425.0,691.0